# Generated by Django 5.0.1 on 2024-01-26 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0004_alter_school_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('period', models.CharField(choices=[('morning', 'Manhã'), ('afternoon', 'Tarde'), ('evening', 'Noite')], default='morning', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated', models.BooleanField(default=True)),
                ('hash_value', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='school.school')),
            ],
        ),
    ]
