# Generated by Django 5.0.1 on 2024-01-26 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classe',
            options={'ordering': ['-name', '-created_at'], 'verbose_name': 'Turma', 'verbose_name_plural': 'Turmas'},
        ),
        migrations.RemoveField(
            model_name='classe',
            name='hash_value',
        ),
    ]
