# Generated by Django 5.0.1 on 2024-01-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='hash_value_tenant',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
