# Generated by Django 5.0.1 on 2024-01-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={},
        ),
        migrations.RemoveField(
            model_name='school',
            name='tenant',
        ),
        migrations.AddField(
            model_name='school',
            name='hash_value',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
