# Generated by Django 5.0.1 on 2024-01-26 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_school_tenant'),
        ('tenant', '0003_tenant_activated_tenant_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='tenant.tenant'),
        ),
    ]
